[package]
name = "cutseq"
version = "0.1.0"
edition = "2024"
readme = "README.md"
license = "MIT"
authors = ["Gaurav Sablok"]
description = "anitomicrobial deep learning"
homepage = "https://codeberg.org/gsablok/cutseq"
repository = "https://codeberg.org/gsablok/cutseq"
keywords = ["bioinformatics","genomics"]


[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
figlet-rs = "0.1.5"
kuva = { version = "0.3.0", features = ["full"] }
rand = "0.10.1"
rayon = "1.11.0"
smartcore = { version = "0.5.0", features = ["ndarray-bindings"] }
tokio = { version = "1.52.3", features = ["full"] }
burn = { version = "0.21", features = ["ndarray", "autodiff"] }
